twig:
    paths:
        - '%kernel.project_dir%/templates'
        - '%kernel.project_dir%/vendor/jtleon/bsw-bundle/Resources/views'
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: 'Leon\BswBundle\Controller\BswBackendController::showExceptionAction'
